#!/bin/sh

function mod() {
   cat "$1" | sed 's/\[fix\]/🐞/g' \
	 | sed 's/\[feat\]/💪/g' \
	 | sed 's/\[docs\]/📚/g' \
	 | sed 's/\[refactor\]/🔨/g' \
	 | sed 's/\[test\]/🚨/g' \
	 | sed 's/\[build\]/👷/g' \
	 | sed 's/\[chore\]/🔧/g' \
	 | sed 's/\[release\]/🔖/g' \
	 | sed 's/\[security\]/🔒/g' \
	 | sed 's/\[config\]/🔧/g' \
	 | sed 's/\[add\]/➕/g' \
	 | sed 's/\[remove\]/➖/g' \
	 | sed 's/\[update\]/🔼/g' \
	 | sed 's/\[hotfix\]/🚑/g'
}

message="$(mod $1)"
echo "$message" > $1
